apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-green
  namespace: __NAMESPACE__
  labels:
    app: aceest-fitness
    strategy: blue-green
    color: green
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: aceest-fitness
      strategy: blue-green
      color: green
  template:
    metadata:
      labels:
        app: aceest-fitness
        strategy: blue-green
        color: green
    spec:
      containers:
        - name: aceest
          image: __GREEN_IMAGE__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: aceest-runtime-config
          env:
            - name: APP_VERSION
              value: __GREEN_VERSION__
            - name: APP_TRACK
              value: green
            - name: APP_EXPERIMENT
              value: control
            - name: APP_COLOR
              value: green
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
