apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-ab-b
  namespace: __NAMESPACE__
  labels:
    app: aceest-fitness
    strategy: ab
    variant: b
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: aceest-fitness
      strategy: ab
      variant: b
  template:
    metadata:
      labels:
        app: aceest-fitness
        strategy: ab
        variant: b
    spec:
      containers:
        - name: aceest
          image: __IMAGE__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: aceest-runtime-config
          env:
            - name: APP_VERSION
              value: __APP_VERSION__
            - name: APP_TRACK
              value: experiment
            - name: APP_EXPERIMENT
              value: variant-b
            - name: APP_COLOR
              value: variant-b
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
