apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aceest-ab-primary
  namespace: __NAMESPACE__
spec:
  ingressClassName: nginx
  rules:
    - host: __APP_HOST__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aceest-ab-a
                port:
                  number: 80
