apiVersion: v1
kind: Service
metadata:
  name: aceest-ab-b
  namespace: __NAMESPACE__
spec:
  selector:
    app: aceest-fitness
    strategy: ab
    variant: b
  ports:
    - name: http
      port: 80
      targetPort: 5000
