apiVersion: v1
kind: Service
metadata:
  name: aceest-rolling
  namespace: __NAMESPACE__
  labels:
    app: aceest-fitness
    strategy: rolling
spec:
  selector:
    app: aceest-fitness
    strategy: rolling
  ports:
    - name: http
      port: 80
      targetPort: 5000
